// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webProj.Models;

namespace webProj.Migrations
{
    [DbContext(typeof(PlesnaSkolaContext))]
    [Migration("20210319222859_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webProj.Models.Ples", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxBrUcenika")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlesnaSkolaID")
                        .HasColumnType("int");

                    b.Property<int>("TrBrUcenika")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlesnaSkolaID");

                    b.ToTable("Plesovi");
                });

            modelBuilder.Entity("webProj.Models.PlesnaSkola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PlesneSkole");
                });

            modelBuilder.Entity("webProj.Models.Ucenik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PLesID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PLesID");

                    b.ToTable("Ucenici");
                });

            modelBuilder.Entity("webProj.Models.Ples", b =>
                {
                    b.HasOne("webProj.Models.PlesnaSkola", "PlesnaSkola")
                        .WithMany("plesovi")
                        .HasForeignKey("PlesnaSkolaID");

                    b.Navigation("PlesnaSkola");
                });

            modelBuilder.Entity("webProj.Models.Ucenik", b =>
                {
                    b.HasOne("webProj.Models.Ples", "PLes")
                        .WithMany("Ucenici")
                        .HasForeignKey("PLesID");

                    b.Navigation("PLes");
                });

            modelBuilder.Entity("webProj.Models.Ples", b =>
                {
                    b.Navigation("Ucenici");
                });

            modelBuilder.Entity("webProj.Models.PlesnaSkola", b =>
                {
                    b.Navigation("plesovi");
                });
#pragma warning restore 612, 618
        }
    }
}
